export * from './createWrapperAndAppendToBody'
export * from './delay'
export * from './getColorStat'
export * from './getPathnameArrayFromUrl'
export * from './getPokemonIdFormated'
export * from './getPokemonTypeBackground'
export * from './joinDataToSearch'
export * from './ruleOfThree'
